name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust-version: [1.68.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}
          
      - name: Build executable
        run: cargo build --release
      
      - name: Install choco
        if: startsWith(matrix.os, 'windows')
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
      - name: Install binutils
        if: startsWith(matrix.os, 'windows')
        run: choco install -y binutils
      
      - name: Create release
        if: startsWith(matrix.os, 'windows')
        run: strip "./target/release/rootoxy.exe"
        
      - name: Final touch
        if: startsWith(matrix.os, 'ubuntu')
        run: strip "./target/release/rootoxy"
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'windows')
        with:
          files: |
            ./target/release/rootoxy.exe
          tag_name: v${{ github.run_number }}
          title: Release v${{ github.run_number }}
          body: |
            Release of version v${{ github.run_number }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: |
            ./target/release/rootoxy
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release of version v${{ github.run_number }}

