name: Pre-Release Build

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust-version: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}

      - name: Build executable
        if: startsWith(matrix.os, 'ubuntu')
        run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --release

      - name: Build executable
        if: startsWith(matrix.os, 'windows')
        run: cargo build --release

      - name: Final touch
        if: startsWith(matrix.os, 'ubuntu')
        run: strip "./target/release/rootoxy" && ldd "./target/release/rootoxy"

      - name: Artifact ${{ matrix.os }}-${{ matrix.rust-version }}
        uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'windows')
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.rust-version }}
          path: |
            ./target/release/rootoxy.exe

      - name: Artifact ${{ matrix.os }}-${{ matrix.rust-version }}
        uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.rust-version }}
          path: |
            ./target/release/rootoxy

  pre-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download ubuntu-latest-stable
        uses: actions/download-artifact@v3
        with:
          name: artifact-ubuntu-latest-stable
          path: ubuntu/stable
      
      - name: Download windows-latest-stable
        uses: actions/download-artifact@v3
        with:
          name: artifact-windows-latest-stable
          path: windows/stable
          
      - name: Publish pre-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./ubuntu/stable/rootoxy
            ./windows/stable/rootoxy.exe
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release of version v${{ github.run_number }}
          prerelease: true
