name: Build and Release

on:
  workflow_dispatch:
    

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust-version: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}

      - name: Build executable
        if: startsWith(matrix.os, 'ubuntu')
        run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --release

      - name: Build executable
        if: startsWith(matrix.os, 'windows')
        run: cargo build --release

      - name: Final touch
        if: startsWith(matrix.os, 'ubuntu')
        run: strip "./target/release/rootoxy" && ldd "./target/release/rootoxy"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'windows')
        with:
          files: |
            ./target/release/rootoxy.exe
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release of version v${{ github.run_number }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: |
            ./target/release/rootoxy
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release of version v${{ github.run_number }}

