name: Rust-ubuntu

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: sudo apt update && sudo apt install tree && rustup update
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose
    - name: Run
      run: cargo run -r
    - name: Final touches
      run: cp "target/release/rootoxy" "." && strip "rootoxy" && ldd "rootoxy"
    - name: List files
      run: tree -h
