name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: sudo apt update && sudo apt install tree
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose
    - name: Run
      run: cargo run -r
    - name: List files
      run: tree -h
